name: jdownloader-vpn
services:
    gluetun:
        stdin_open: true
        tty: true
        restart: always
        container_name: jdownloader-vpn
        cap_add:
            - NET_ADMIN
        ports:
            - 49167:5800
            - 49166:5900
        environment:
            - VPN_SERVICE_PROVIDER=mullvad
            - VPN_TYPE=openvpn
            - OPENVPN_USER=xxxxxxxxxxxx
            - SERVER_COUNTRIES=Switzerland
        image: qmcgaw/gluetun