name: calibre-web
services:
    calibre-web:
        container_name: calibre-web-3
        networks:
            qnet-static-eth0-xxxx:
                ipv4_address: xxx.xxx.xxx.xxx
        mac_address: 02:42:c0:a8:fa:13
        environment:
            - PUID=1006
            - PGID=100
            - TZ=Europe/Berlin
            - DOCKER_MODS=linuxserver/mods:universal-calibre
            - OAUTHLIB_RELAX_TOKEN_SCOPE=1
        volumes:
            - /share/Container-shares/calibre/config:/config
            - /share/Container-shares/calibre/library:/books
        restart: always
        image: lscr.io/linuxserver/calibre-web:latest
networks:
    qnet-static-eth0-xxxx:
        external: true
        name: qnet-static-eth0-xxxx