name: calibre
services:
    calibre:
        container_name: calibre-3
        security_opt:
            - seccomp=unconfined
        networks:
            qnet-static-eth0-xxxx:
                ipv4_address: xxx.xxx.xxx.xxx
        mac_address: 02:42:c0:a8:fa:14
        environment:
            - PUID=1006
            - PGID=100
            - TZ=Europe/Berlin
        volumes:
            - /share/Container-shares/calibre/library:/config
            - /share/ebooks:/mnt
        restart: always
        image: lscr.io/linuxserver/calibre:latest
networks:
    qnet-static-eth0-xxxx:
        external: true
        name: qnet-static-eth0-xxxxx